# Generated by Django 4.1.5 on 2023-03-28 20:44

import django.core.validators
from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customerpoints'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('code', models.CharField(default=users.models.random_code, max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('proxy_uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
