# Generated by Django 4.1.5 on 2023-03-29 16:14

from django.db import migrations, models
import users.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_phoneauthentication_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAuthentication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('code', models.CharField(default=users.models.random_code, max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('proxy_uuid', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
