# Generated by Django 4.1.5 on 2023-03-30 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='item1',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='item1_points',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='item2',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='item2_points',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='item3',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='item3_points',
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('num_points', models.IntegerField(null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.restaurant')),
            ],
        ),
    ]
