# Generated by Django 4.1.5 on 2023-03-31 19:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_restaurantqr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantqr',
            name='code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='restaurantqr',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.restaurant'),
        ),
    ]
