# Generated by Django 4.1.5 on 2023-04-02 02:03

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_restaurantqr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=users.models.S3MediaStorage(), upload_to='profiles/'),
        ),
    ]
