# Generated by Django 4.1.5 on 2023-04-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_restaurantqr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
