# Generated by Django 4.1.5 on 2023-04-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_customer_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_image',
            field=models.FileField(blank=True, null=True, upload_to='restaurants/'),
        ),
    ]
