# Generated by Django 4.1.5 on 2023-04-03 03:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_restaurant_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpoints',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
