# Generated by Django 4.1.5 on 2023-04-06 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customerpoints_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantqr',
            name='default_qr',
            field=models.CharField(default='de635a5f-92e4-4827-8b79-d1cd89733206|https://apps.apple.com/app/punchme/id6447275121', max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurantqr',
            name='code',
            field=models.UUIDField(default=uuid.UUID('de635a5f-92e4-4827-8b79-d1cd89733206')),
        ),
    ]
