# Generated by Django 4.1.5 on 2023-04-07 17:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_restaurantqr_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpoints',
            name='give_point_eligible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurantqr',
            name='code',
            field=models.UUIDField(default=uuid.UUID('22c971a4-d743-48f6-8c8f-742681650e53')),
        ),
        migrations.AlterField(
            model_name='restaurantqr',
            name='default_qr',
            field=models.CharField(default='22c971a4-d743-48f6-8c8f-742681650e53|https://apps.apple.com/app/punchme/id6447275121', max_length=255),
        ),
    ]
