# Generated by Django 4.1.5 on 2023-04-07 23:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_restaurantqr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantqr',
            name='code',
            field=models.UUIDField(default=uuid.UUID('0b430e02-1c07-4c56-8723-82c8469f7acc')),
        ),
        migrations.AlterField(
            model_name='restaurantqr',
            name='default_qr',
            field=models.CharField(default='0b430e02-1c07-4c56-8723-82c8469f7acc|https://apps.apple.com/app/punchme/id6447275121', max_length=255),
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_notifications', to='users.customer')),
            ],
        ),
    ]
