# Generated by Django 4.1.5 on 2023-04-07 23:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_restaurantqr_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantqr',
            name='default_qr',
        ),
        migrations.AlterField(
            model_name='restaurantqr',
            name='code',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
