# Generated by Django 4.1.5 on 2023-04-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_remove_restaurantqr_default_qr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushtoken',
            name='device_id',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pushtoken',
            name='token',
            field=models.CharField(max_length=255),
        ),
    ]
