# Generated by Django 4.1.5 on 2023-04-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_pushtoken_device_id_alter_pushtoken_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushtoken',
            name='device_id',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
