# Generated by Django 4.1.5 on 2023-04-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_pushtoken_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pushtoken',
            name='device_id',
        ),
    ]
