# Generated by Django 4.1.5 on 2023-04-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='employee_code',
            field=models.PositiveIntegerField(default=None, verbose_name='employee code'),
        ),
    ]
